In [47]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

df = pd.read_csv('affairs.csv')
df.head()

,affair_count,is_male,age,years_married,have_kids,religiousness_1to5,years_of_education,hollingshead_occupation_code,marriage_rating_1to5
0,0,1,37.0,10.00,0,3,18,7,4
1,0,0,27.0,4.00,0,4,14,6,4
2,0,0,32.0,15.00,1,1,12,1,4
3,0,1,57.0,15.00,1,5,18,6,5
4,0,1,22.0,0.75,0,2,17,6,3

In [49]:
y = df['hollingshead_occupation_code'] 
X = df[['have_kids','years_of_education']]
X = sm.add_constant(X)

In [51]:
model = sm.MNLogit(y, X)
result = model.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 1.384473
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                               MNLogit Regression Results
========================================================================================
Dep. Variable:     hollingshead_occupation_code   No. Observations:                  601
Model:                                  MNLogit   Df Residuals:                      583
Method:                                     MLE   Df Model:                           12
Date:                          Wed, 03 Apr 2024   Pseudo R-squ.:                  0.1529
Time:                                  12:20:58   Log-Likelihood:                -832.07
converged:                                 True   LL-Null:                       -982.21
Covariance Type:                      nonrobust   LLR p-value:                 4.114e-57
==================================================================================================
hollingshead_occupation_code=2       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              1.8899      2.238      0.844      0.398      -2.497       6.277
have_kids                          0.4318      1.085      0.398      0.691      -1.694       2.558
years_of_education                -0.3202      0.143     -2.235      0.025      -0.601      -0.039
--------------------------------------------------------------------------------------------------
hollingshead_occupation_code=3       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              1.8286      1.351      1.353      0.176      -0.820       4.477
have_kids                         -1.6281      0.409     -3.983      0.000      -2.429      -0.827
years_of_education                -0.1043      0.089     -1.176      0.240      -0.278       0.070
--------------------------------------------------------------------------------------------------
hollingshead_occupation_code=4       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                             -1.6338      1.244     -1.314      0.189      -4.071       0.804
have_kids                         -1.4628      0.373     -3.922      0.000      -2.194      -0.732
years_of_education                 0.1485      0.079      1.881      0.060      -0.006       0.303
--------------------------------------------------------------------------------------------------
hollingshead_occupation_code=5       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                             -5.8452      1.059     -5.517      0.000      -7.922      -3.769
have_kids                         -1.1337      0.326     -3.477      0.001      -1.773      -0.495
years_of_education                 0.4700      0.066      7.119      0.000       0.341       0.599
--------------------------------------------------------------------------------------------------
hollingshead_occupation_code=6       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                            -15.2671      1.490    -10.248      0.000     -18.187     -12.347
have_kids                         -0.8439      0.376     -2.244      0.025      -1.581      -0.107
years_of_education                 0.9796      0.088     11.096      0.000       0.807       1.153
--------------------------------------------------------------------------------------------------
hollingshead_occupation_code=7       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                            -11.8191      2.695     -4.386      0.000     -17.100      -6.538
have_kids                         -0.1063      0.825     -0.129      0.897      -1.724       1.511
years_of_education                 0.6154      0.156      3.957      0.000       0.311       0.920
==================================================================================================
"""

In [57]:
predictions = result.predict(X)
predictions

            0         1         2         3         4         5         6
0    0.033787  0.000702  0.032149  0.095557  0.461922  0.359791  0.016093
1    0.155793  0.011655  0.225028  0.243249  0.324974  0.032971  0.006329
2    0.471190  0.102987  0.164599  0.126593  0.123557  0.006046  0.005027
3    0.088640  0.002837  0.016556  0.058058  0.390017  0.405930  0.037961
4    0.057727  0.001653  0.060970  0.140731  0.493252  0.230809  0.014859
..        ...       ...       ...       ...       ...       ...       ...
596  0.471190  0.102987  0.164599  0.126593  0.123557  0.006046  0.005027
597  0.088640  0.002837  0.016556  0.058058  0.390017  0.405930  0.037961
598  0.153449  0.006765  0.031813  0.086634  0.421975  0.263849  0.035514
599  0.088640  0.002837  0.016556  0.058058  0.390017  0.405930  0.037961
600  0.390749  0.045016  0.110788  0.141291  0.262319  0.035563  0.014273

[601 rows x 7 columns]