In [170]:
import pandas as pd
new = pd.read_csv('newleads.csv')
used = pd.read_csv('usedleads.csv')
new = new[['Lead Source Group', 'Total Leads', 'Good Leads','Sold from Leads']]
new.columns = ['Lead Source', 'New Vehicle Leads', 'Good New Vehicle Leads', 'New Vehicles Sold']
used = used[['Lead Source Group', 'Total Leads', 'Good Leads','Sold from Leads']]
used.columns = ['Lead Source', 'Used Vehicle Leads', 'Good Used Vehicle Leads','Used Vehicles Sold']
df = pd.merge(new,used,on="Lead Source", how="outer")
df = df.fillna(0)
df['Total Leads'] = df['New Vehicle Leads'] + df['Used Vehicle Leads']
df['Total Good Leads'] = df['Good New Vehicle Leads'] + df['Good Used Vehicle Leads']
df['Total Vehicles Sold'] = df['New Vehicles Sold'] + df['Used Vehicles Sold']
df.to_csv('EOM Report Final.csv')

,Lead Source,New Vehicle Leads,Good New Vehicle Leads,New Vehicles Sold,Used Vehicle Leads,Good Used Vehicle Leads,Used Vehicles Sold,Total Leads,Total Good Leads,Total Vehicles Sold
0,GM 3rd Party,108.0,79.0,1.0,0.0,0.0,0.0,108.0,79.0,1.0
1,Truecar,107.0,88.0,0.0,0.0,0.0,0.0,107.0,88.0,0.0
2,KBB,60.0,50.0,1.0,0.0,0.0,0.0,60.0,50.0,1.0
3,Edumunds,24.0,14.0,0.0,1.0,0.0,0.0,25.0,14.0,0.0
4,Website Chat - Gubagoo,22.0,18.0,0.0,1.0,0.0,0.0,23.0,18.0,0.0

In [144]:
sld = pd.read_csv('soldlog.csv')
sld.head()

,Stock Number,Sold Date,Lead Source Group,Inventory Type
0,30461-9,06/03/2023 04:54 PM,GM 3rd Party,Used
1,P5765,06/09/2023 05:27 PM,GM 3rd Party,Used
2,P5731-2,06/28/2023 05:51 PM,Facebook Ads,Used
3,30501-1,06/10/2023 03:45 PM,Website - CDK Global - Form Unknown,Used
4,P5749-1,06/02/2023 03:32 PM,Website Chat - Gubagoo,Used

In [164]:
sldn = sld[sld['Inventory Type'].str.contains('New')]
sldn = sldn.groupby('Lead Source Group').count()
sldn = sldn[['Stock Number']]
sldn.columns = ['New Vehicles Sold']
sldn = sldn.fillna(0)

In [165]:
sldu = sld[sld['Inventory Type'].str.contains('Used')]
sldu = sldu.groupby('Lead Source Group').count()
sldu = sldu[['Stock Number']]
sldu.columns = ['Used Vehicles Sold']
sldu = sldu.fillna(0)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [129]:
un = pd.merge(n,u,on="Lead Source Group", how="outer")


un

#merge and write to csv
#final = df6.join(un2,how='left')
#final = final.rename(columns = {'New':'Sold Log Count New','Used':'Sold Log Count Used'})

#df7 = pd.merge(dfn5,dfu5,on="Source", how="outer")

,Stock Number_x,Sold Date_x,Inventory Type_x,Stock Number_y,Sold Date_y,Inventory Type_y
Lead Source Group,,,,,,
AutoTrader,1.0,1.0,1.0,1,1,1
Capital One - Dealer Navigator,2.0,2.0,2.0,7,7,7
CarFax,1.0,1.0,1.0,2,2,2
Edumunds,0.0,1.0,1.0,1,1,1
GM 3rd Party,1.0,1.0,1.0,2,2,2
KBB,1.0,1.0,1.0,3,3,3
Lot Up,5.0,5.0,5.0,27,27,27
Phone,1.0,1.0,1.0,14,14,14
Website - General / Misc,3.0,4.0,4.0,23,23,23
Bankruptcy Resource Group,NaN,NaN,NaN,1,1,1
CarGurus,NaN,NaN,NaN,5,5,5
Cars.com,NaN,NaN,NaN,1,1,1
CarsForSale.com,NaN,NaN,NaN,1,1,1
Credit Bureau Connection,NaN,NaN,NaN,7,7,7
Facebook,NaN,NaN,NaN,3,3,3
Facebook Ads,NaN,NaN,NaN,2,2,2
Referral,NaN,NaN,NaN,3,3,3
Repeat Customer,NaN,NaN,NaN,1,1,1
Terry Sources,NaN,NaN,NaN,4,4,4
Truecar,NaN,NaN,NaN,2,2,2
Website - CDK Global - Form Unknown,NaN,NaN,NaN,7,7,7
Website - Price Watch,NaN,NaN,NaN,1,1,1
Website Chat - Gubagoo,NaN,NaN,NaN,3,3,3